name: word_list_coodesh_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_crashlytics: ^3.3.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

